### PR TITLE
Update getCOPDataFromDATIM.R

### PR DESCRIPTION
**Pull request by sam-bao**
getDatasetUids is up to date so getCOPDataFromDATIM should now work for COP21.

We can use the Zamiba test import to cop test to help test.

`getCOPDataFromDATIM(datimutils::getOrgUnits("Zambia", by = name), cop_year = 2021, stream = c("mer_targets", "subnat_targets"))`

and

`getCOPDataFromDATIM(datimutils::getOrgUnits("Zambia", by = name), cop_year = 2020, stream = c("impatt", "subnat_targets"))`

Should return the data from the zambia test import

### CODE REVIEW

**Comment by jacksonsj** [comment]
Ran the following:

```
datapackr::loginToDATIM("~/.secrets/datim.json")

[1] "Scott Jackson is logged in"
[1] "Successfully logged into DATIM"

zambia_2021 <- getCOPDataFromDATIM(datimutils::getOrgUnits("Zambia", by = name), cop_year = 2021, stream = c("mer_targets", "subnat_targets"))

zambia_2020 <- getCOPDataFromDATIM(datimutils::getOrgUnits("Zambia", by = name), cop_year = 2020, stream = c("impatt", "subnat_targets"))
```

`zambia_2021` returned with 0 rows; `zambia_2020` with 13,458. Investigating now.

**Comment by jacksonsj** [comment]
Ok, so after changing to the correct secrets file, and correcting the `stream` parameter to `streams` (see below), I'm now getting 63,874 rows for `zambia_2021` and 12,876 rows for `zambia_2020`.

That still means some rows are dropping — original import file had 81,482 rows, compared to the combined 76,748 returning here — but that's the point of this function, to allow us to investigate what's being dropped.

```
datapackr::loginToDATIM("~/.secrets/cop-test.json")

zambia_2021 <- getCOPDataFromDATIM(datimutils::getOrgUnits("Zambia", by = name), cop_year = 2021, streams = c("mer_targets", "subnat_targets"))

zambia_2020 <- getCOPDataFromDATIM(datimutils::getOrgUnits("Zambia", by = name), cop_year = 2020, streams = c("impatt", "subnat_targets"))
```

**Comment by jacksonsj** [comment]
Including analysis of differences between DATIM imported data and original import file for Zambia, as the results could pertain to issues with this function:

----
- 134 rows where DATIM data appears to have rounded to nearest even instead of nearest integer -- cases with values ended in `0.00.....5`)

@jason-p-pickering - This does not appear to have been an issue on either the `datapackr` side when producing the import file, nor in Max's script for importing it. Do you know how DATIM handles rounding of decimals ending in `...5`? Round to even, or round to nearest integer? If round to even, I recommend we update our import prep scripts to mimic to avoid discrepancies between DATIM and import files even in these cases with 5+ decimal places. (With HIV_PREV, that could still mean swings of 100s of people in some of these countries.)

----
- The following are present in import file, but not in DATIM:
    - `DIAGNOSED_SUBNAT.T`
    - `HTS_SELF.T` for mechanism `106160`
    - `IMPATT.PRIORITY_SNU.T`
    - `PrEP_CURR.T` for mechanism `106160`
    - `PrEP_NEW.T` for mechanism `106160`
    - `TX_CURR_SUBNAT.T`

See below for notes about mechanism `106160`.

In looking closer at `TX_CURR_SUBNAT.T`, there doesn't appear to be any pattern explaining why some `TX_CURR_SUBNAT.T` data imported and other data did not. We're using correct `dataElement` and `categoryOptionCombos` in our mapping, these are correct in the import file, and sometimes these were imported into DATIM, while in other PSNUs, the same dataElement and categoryOptionCombo were not imported. I'm stumped here.

Same odd pattern for `DIAGNOSED_SUBNAT.T`.

For Prioritization, only explanation I can think of is that we've not opened this dataset to allow Prioritizations to be imported against FY22, which we'll need to. @jason-p-pickering - Is this something we can turn on in `cop-test`, or something deeper only Tim/Kyle can fix?

----

 - The following seem to have mutated somehow on import:
    - `OVC_HIVSTAT.T`: mechanism `106160` seems to have been mutated to `18346`
    - `OVC_SERV.Active.T` mechanism `106160` seems to have been mutated to `18346`
    - `PP_PREV.T` mechanism `106160` seems to have been mutated to `18346

On first glance, mechanism `106160` does not appear anywhere in either DATIM prod or in `cop-test`. It also does not seem to appear in the FI-NG feed.
- I'll check with Tim on this one.
- @maxwellchandler - When you imported, did you get an alert about attempting to import against a non-valid mechanism? - @jason-p-pickering - can you confirm you also do not see mechanism `106160` anywhere?

`18346` does appear in prod and `cop-test`, but it's unclear how `106160` got swapped for this during/after import. @jason-p-pickering - any ideas?

**Comment by jacksonsj** [comment]
@sam-bao - As far as I can tell, the issues above don't implicate the code in this branch. Pushing this into `dev` now.

**Review by jacksonsj — APPROVED** [review]

**Comment by jason-p-pickering** [comment]
@jacksonsj I have looked into this on cop-test. See my full message in Slack, but the basic conclusion is that DATIM does not perform ( or at least I cannot reproduce) any rounding. All import values are handled as text, and should not be modulated in anyway by the server on import. So, while having some additional functionality in `round_trunc` may be good, I just wanted to be clear that DATIM itself is not doing any of this rounding which may have been observed. I suspect this was part of the import process itself. 

FYI @maxwellchandler @sam-bao

**Comment by jacksonsj** [comment]
For where the output from getCOPDataFromDATIM affects `compareData_DatapackVsDatim`, I've made updates in that function to align. See below for results of tests showing this has worked using this [Zambia file](https://pepfar.sharepoint.com/:x:/r/sites/PRIMEInformationSystems/Shared%20Documents/COP21%20Systems%20Support/Data%20Pack/Testing/Appended%20PSNUxIM/Data%20Pack_Zambia_20210208.xlsx?d=w6db10de296f942608fa3698e194bb3c8&csf=1&web=1&e=DOHMca):

```
> library(datapackr)
> library(magrittr)
> 
> datapackr::loginToDATIM("~/.secrets/datim.json")
[1] "Scott Jackson is logged in"
[1] "Successfully logged into DATIM"
> 
> d <- unPackTool(cop_year = 2021)
[1] "Please choose a file."
[1] "Checking comments..."                                                                                                                                                                                                         
[1] "Checking structure..."
[1] "Checking for any missing tabs..."
[1] "Unpacking sheets..."
[1] "Prioritization"
[1] "Cascade"                                                                                                                                                                                                                      
[1] "PMTCT"                                                                                                                                                                                                                        
[1] "EID"                                                                                                                                                                                                                          
[1] "TB"                                                                                                                                                                                                                           
[1] "VMMC"                                                                                                                                                                                                                         
[1] "HTS"                                                                                                                                                                                                                          
[1] "CXCA"                                                                                                                                                                                                                         
[1] "HTS_RECENT"                                                                                                                                                                                                                   
[1] "TX_TB_PREV"                                                                                                                                                                                                                   
[1] "PP"                                                                                                                                                                                                                           
[1] "OVC"                                                                                                                                                                                                                          
[1] "GEND"                                                                                                                                                                                                                         
[1] "AGYW"                                                                                                                                                                                                                         
[1] "PrEP"                                                                                                                                                                                                                         
[1] "KP"                                                                                                                                                                                                                           
[1] "KP Validation"                                                                                                                                                                                                                
[1] "KP_MAT"                                                                                                                                                                                                                       
[1] "Separating datasets..."                                                                                                                                                                                                       
[1] "Unpacking the PSNUxIM tab..."
Joining, by = c("PSNU", "indicator_code", "Age", "Sex", "KeyPop", "psnuid")                                                                                                                                                        
[1] "Creating analytics..."
VALIDATION ISSUES: 

*********************
KEY:
- WARNING!: Problematic, but doesn't stop us from processing your tool. May waive with approval from PPM and DUIT.
- ERROR!: You MUST address these issues and resubmit your tool.
*********************

1 :  WARNING! In tab Cascade, 1 ALTERED FORMULAS: Altering formulas without DUIT and PPM approval may lead to programmatic and technical issues in your Data Pack. Note that this may be due to a formula being deleted or overwritten, or a manual fix not being applied. Affected columns and the number of violations are listed below. ->  
	* DIAGNOSED_SUBNAT.T:  2808

2 :  ERROR! In tab Cascade: NEGATIVE VALUES found in the following columns! Ensure all values entered against FY22 Targets are whole, positive, numeric values. These will be removed. -> 
	* DIAGNOSED_SUBNAT.T_1
	* DIAGNOSED_SUBNAT.T

3 :  WARNING! In tab PMTCT, 1 ALTERED FORMULAS: Altering formulas without DUIT and PPM approval may lead to programmatic and technical issues in your Data Pack. Note that this may be due to a formula being deleted or overwritten, or a manual fix not being applied. Affected columns and the number of violations are listed below. ->  
	* PMTCT_STAT_SUBNAT.D.T:  1053

4 :  WARNING! In tab PMTCT: DECIMAL VALUES found in the following columns! Ensure all values entered against FY22 Targets are whole, positive, numeric values. (The only exception to this rule may be HIV_PREV.) These will be rounded. -> 
	* PMTCT_STAT_SUBNAT.D.T

5 :  WARNING! In tab KP, MISSING COLUMNS: Please ensure no columns have been deleted or renamed from the original Data Pack you have received. ->  
	* KP_ESTIMATES.Total.T_1
	* KP_ESTIMATES.Pos.T_1
	* KP_ESTIMATES.Prev.T_1

6 :  WARNING! Your Data Pack may need a new PSNUxIM tab. Along with this warning, you should also receive an updated copy of your Data Pack with new rows added to the bottom of your PSNUxIM tab containing any previously missing data combinations. NOTE that adding data to your PSNUxIM tab could significantly increase the size of your Data Pack, so it is recommended to wait to update your Data Pack's PSNUxIM tab until after all changes to other tabs of your Data Pack are complete.  Once all other updates are complete, you may return here to update your PSNUxIM tab at any time.

7 :  WARNING: 630 cases where rounding based on PSNUxIM distributions has caused a small amount of variation from original targets set in other sheets. A small amount of rounding may be unavoidable given the nature of the target-setting process. You can review these cases in the FlatPack provided as an output from this app. To resolve these cases, please review the PSNUxIM tab to identify and address cases where multiplication of distribution percentages against FY22 Targets has caused rounding error. You may address this by gradually altering distribution percentages to fine tune allocations against one or more mechanisms. For additional guidance, see the Data Pack User Guide.

8 :  ERROR!: 13752 cases where distributed total across all mechanisms and Dedupe is either more or less than PSNU-level Target. To identify these, go to your PSNUxIM tab and filter the Rollup column to find cases where this is not equal to the Data Pack Target column (highlighted red). NOTE that this may be due to invalid mechanism names in row 14 of your PSNUxIM tab. For reference, this has affected the following indicators. -> 
	* HTS_INDEX_COM.New.Neg.T
	* HTS_INDEX_COM.New.Pos.T
	* HTS_INDEX_FAC.New.Neg.T
	* HTS_INDEX_FAC.New.Pos.T
	* HTS_RECENT.EW.T
	* HTS_RECENT.IndexCom.T
	* HTS_RECENT.IndexFac.T
	* HTS_RECENT.Inpat.T
	* HTS_RECENT.KP.T
	* HTS_RECENT.MobileCom.T
	* HTS_RECENT.Other.T
	* HTS_RECENT.OtherCom.T
	* HTS_RECENT.PMTCT_STAT.T
	* HTS_RECENT.PostANC1.T
	* HTS_RECENT.STI.T
	* HTS_RECENT.TB.T
	* HTS_RECENT.VCT.T
	* HTS_RECENT.VMMC.T
	* HTS_TST.EW.Neg.T
	* HTS_TST.EW.Pos.T
	* HTS_TST.Inpat.Neg.T
	* HTS_TST.Inpat.Pos.T
	* HTS_TST.KP.Pos.T
	* HTS_TST.Maln.Neg.T
	* HTS_TST.Maln.Pos.T
	* HTS_TST.MobileCom.Neg.T
	* HTS_TST.MobileCom.Pos.T
	* HTS_TST.Other.Neg.T
	* HTS_TST.Other.Pos.T
	* HTS_TST.OtherCom.Neg.T
	* HTS_TST.OtherCom.Pos.T
	* HTS_TST.Peds.Neg.T
	* HTS_TST.Peds.Pos.T
	* HTS_TST.PostANC1.Neg.T
	* HTS_TST.PostANC1.Pos.T
	* HTS_TST.STI.Neg.T
	* HTS_TST.STI.Pos.T
	* HTS_TST.VCT.Neg.T
	* HTS_TST.VCT.Pos.T
	* KP_PREV.T
	* OVC_SERV.Grad.T
	* PMTCT_ART.Already.T
	* PMTCT_ART.New.T
	* PMTCT_STAT.N.KnownPos.T
	* PMTCT_STAT.N.New.Neg.T
	* PMTCT_STAT.N.New.Pos.T
	* TB_ART.Already.T
	* TB_ART.New.T
	* TB_PREV.D.New.T
	* TB_PREV.N.New.T
	* TB_STAT.N.KnownPos.T
	* TB_STAT.N.New.Neg.T
	* TB_STAT.N.New.Pos.T
	* TX_CURR.KP.T
	* TX_CURR.T
	* TX_NEW.KP.T
	* TX_NEW.T
	* TX_PVLS.D.KP.T
	* TX_PVLS.D.Routine.T
	* TX_PVLS.N.KP.T
	* TX_PVLS.N.Routine.T
	* TX_TB.D.New.Neg.T
	* TX_TB.D.New.Pos.T
	* VMMC_CIRC.Pos.T

9 :  ERROR occurred. Negative values present in SUBNAT/IMPATT data.> 
> r <- compareData_DatapackVsDatim(d)
Joining, by = c("dataElement", "orgUnit", "categoryOptionCombo")
Joining, by = c("dataElement", "period", "orgUnit", "categoryOptionCombo", "attributeOptionCombo")
> r
$psnu_x_im_wo_dedup
# A tibble: 71,454 x 8
   psnu             data_element                                 disagg                  attributeOptionCombo datapack_value datim_value difference effect
   <chr>            <chr>                                        <chr>                   <chr>                         <dbl>       <dbl>      <dbl> <chr> 
 1 _Military Zambia CXCA_SCRN (N, DSD, Age/Sex/HIVStatus) TARGET 25-29, Female, Positive 14507                           599          NA        599 Update
 2 _Military Zambia CXCA_SCRN (N, DSD, Age/Sex/HIVStatus) TARGET 25-29, Female, Positive 85087                          1796          NA       1796 Update
 3 _Military Zambia CXCA_SCRN (N, DSD, Age/Sex/HIVStatus) TARGET 30-34, Female, Positive 14507                           661          NA        661 Update
 4 _Military Zambia CXCA_SCRN (N, DSD, Age/Sex/HIVStatus) TARGET 30-34, Female, Positive 85087                          1982          NA       1982 Update
 5 _Military Zambia CXCA_SCRN (N, DSD, Age/Sex/HIVStatus) TARGET 35-39, Female, Positive 14507                           690          NA        690 Update
 6 _Military Zambia CXCA_SCRN (N, DSD, Age/Sex/HIVStatus) TARGET 35-39, Female, Positive 85087                          2070          NA       2070 Update
 7 _Military Zambia CXCA_SCRN (N, DSD, Age/Sex/HIVStatus) TARGET 40-44, Female, Positive 14507                           444          NA        444 Update
 8 _Military Zambia CXCA_SCRN (N, DSD, Age/Sex/HIVStatus) TARGET 40-44, Female, Positive 85087                          1331          NA       1331 Update
 9 _Military Zambia CXCA_SCRN (N, DSD, Age/Sex/HIVStatus) TARGET 45-49, Female, Positive 14507                           444          NA        444 Update
10 _Military Zambia CXCA_SCRN (N, DSD, Age/Sex/HIVStatus) TARGET 45-49, Female, Positive 85087                          1331          NA       1331 Update
# … with 71,444 more rows

$psnu_w_dedup
# A tibble: 55,088 x 6
   psnu           data_element                                    disagg                                                              datapack_value datim_value difference
   <chr>          <chr>                                           <chr>                                                                        <dbl>       <dbl>      <dbl>
 1 Sioma District TX_TB (D, DSD, Age/Sex/TBScreen/ART/HIV) TARGET 15+, Female, TB Screen - Positive, Life-long ART, New, Positive                 11          NA         11
 2 Sioma District TX_TB (D, DSD, Age/Sex/TBScreen/ART/HIV) TARGET 15+, Female, TB Screen - Negative, Life-long ART, Already, Positive           2063          NA       2063
 3 Sioma District TX_TB (D, DSD, Age/Sex/TBScreen/ART/HIV) TARGET <15, Male, TB Screen - Negative, Life-long ART, New, Positive                    9          NA          9
 4 Sioma District TX_TB (D, DSD, Age/Sex/TBScreen/ART/HIV) TARGET <15, Female, TB Screen - Negative, Life-long ART, New, Positive                  9          NA          9
 5 Sioma District TX_TB (D, DSD, Age/Sex/TBScreen/ART/HIV) TARGET 15+, Female, TB Screen - Negative, Life-long ART, New, Positive                 81          NA         81
 6 Sioma District TX_TB (D, DSD, Age/Sex/TBScreen/ART/HIV) TARGET <15, Male, TB Screen - Negative, Life-long ART, Already, Positive              123          NA        123
 7 Sioma District TX_TB (D, DSD, Age/Sex/TBScreen/ART/HIV) TARGET <15, Female, TB Screen - Positive, Life-long ART, Already, Positive              6          NA          6
 8 Sioma District TX_TB (D, DSD, Age/Sex/TBScreen/ART/HIV) TARGET 15+, Male, TB Screen - Negative, Life-long ART, New, Positive                  169          NA        169
 9 Sioma District TX_TB (D, DSD, Age/Sex/TBScreen/ART/HIV) TARGET 15+, Male, TB Screen - Positive, Life-long ART, Already, Positive               92          NA         92
10 Sioma District TX_TB (D, DSD, Age/Sex/TBScreen/ART/HIV) TARGET 15+, Male, TB Screen - Negative, Life-long ART, Already, Positive             1171          NA       1171
# … with 55,078 more rows

$updates
# A tibble: 71,454 x 6
   dataElement period  orgUnit     categoryOptionCombo attributeOptionCombo datapack_value
   <chr>       <chr>   <chr>       <chr>               <chr>                         <dbl>
 1 hfR9r70Fk99 2021Oct y0cygdhumHI bRvIkMjZ1jm         14507                           599
 2 hfR9r70Fk99 2021Oct y0cygdhumHI bRvIkMjZ1jm         85087                          1796
 3 hfR9r70Fk99 2021Oct y0cygdhumHI qZIQc8r8jfO         14507                           661
 4 hfR9r70Fk99 2021Oct y0cygdhumHI qZIQc8r8jfO         85087                          1982
 5 hfR9r70Fk99 2021Oct y0cygdhumHI MOilrKBIYU3         14507                           690
 6 hfR9r70Fk99 2021Oct y0cygdhumHI MOilrKBIYU3         85087                          2070
 7 hfR9r70Fk99 2021Oct y0cygdhumHI ArRidY0sHkk         14507                           444
 8 hfR9r70Fk99 2021Oct y0cygdhumHI ArRidY0sHkk         85087                          1331
 9 hfR9r70Fk99 2021Oct y0cygdhumHI RGr7QRtlrAk         14507                           444
10 hfR9r70Fk99 2021Oct y0cygdhumHI RGr7QRtlrAk         85087                          1331
# … with 71,444 more rows

$deletes
# A tibble: 0 x 6
# … with 6 variables: dataElement <chr>, period <chr>, orgUnit <chr>, categoryOptionCombo <chr>, attributeOptionCombo <chr>, datim_value <dbl>
```

**Comment by jacksonsj** [comment]
I've also updated and tested `compareData_OpuDatapackVsDatim, per DP-71. Using [this file for Mozambique](https://pepfar.sharepoint.com/:x:/r/sites/Mozambique/HQ%20Collaboration/COP20%20CDC%20OPU%20DataPack%20Tool_210302/OPU%20Data%20Pack_Mozambique_Dec142020_EAW210302.xlsx?d=w545f2d547cf549b1a1f642551a0f1f1f&csf=1&web=1&e=lUfHpP), which was imported to DATIM prod on 3/4/21, I get the below:

```
> # For COP20 OPU Data Pack
> datapackr::loginToDATIM("~/.secrets/datim.json")
[1] "Scott Jackson is logged in"
[1] "Successfully logged into DATIM"
> 
> d <- unPackTool(tool = "OPU Data Pack",
+                 cop_year = 2020)
[1] "Please choose a file."
[1] "Checking for any missing tabs..."                                                                                                                                                                                             
>                                                                                                                                                                                                                                  
> r <- compareData_OpuDatapackVsDatim(d)
|======================================================================================================================================================================================================================| 100%   14 MB
Joining, by = c("dataElement", "period", "orgUnit", "categoryOptionCombo", "attributeOptionCombo")
> r
$updates
# A tibble: 0 x 6
# … with 6 variables: dataElement <chr>, period <chr>, orgUnit <chr>, categoryOptionCombo <chr>, attributeOptionCombo <chr>, value <dbl>

$deletes
# A tibble: 0 x 6
# … with 6 variables: dataElement <chr>, period <chr>, orgUnit <chr>, categoryOptionCombo <chr>, attributeOptionCombo <chr>, value <dbl>

$dedupes
# A tibble: 34,507 x 6
   dataElement period  orgUnit     categoryOptionCombo attributeOptionCombo value
   <chr>       <chr>   <chr>       <chr>               <chr>                <dbl>
 1 Ea3rt2Nb0QG 2020Oct SnbIkc5HFdC prSfkXlKE2r         00000                    0
 2 Ea3rt2Nb0QG 2020Oct SnbIkc5HFdC yDfHPRaDxwe         00000                    0
 3 Ea3rt2Nb0QG 2020Oct SnbIkc5HFdC PFWJho4V0Bq         00000                    0
 4 Ea3rt2Nb0QG 2020Oct SnbIkc5HFdC X8pGUJitiVE         00000                    0
 5 Ea3rt2Nb0QG 2020Oct SnbIkc5HFdC frIsAnU6KOZ         00000                    0
 6 Ea3rt2Nb0QG 2020Oct SnbIkc5HFdC RnKGfzcpePu         00000                    0
 7 Ea3rt2Nb0QG 2020Oct SnbIkc5HFdC ltwvGENFQ0F         00000                    0
 8 Ea3rt2Nb0QG 2020Oct SnbIkc5HFdC QZCuRi4MOLN         00000                    0
 9 Ea3rt2Nb0QG 2020Oct SnbIkc5HFdC hyVPPHNEwLB         00000                    0
10 Ea3rt2Nb0QG 2020Oct SnbIkc5HFdC az6WUd9cNW8         00000                    0
# … with 34,497 more rows
```

**Review by jacksonsj — APPROVED** [review]

**Pull request merged**
