### PR TITLE
DP-765: COP21/22 OPU tool generation & processing

### PR DESCRIPTION
**Pull request by cnemarich**
### Summary of Proposed Changes
- Implements the ability to pack and unpack COP22 OPU tools

### Related Issues
- DP-765

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

### CODE REVIEW

**Comment by sam-bao** [comment]
@flopez-bao  @JordanBalesBAO I have started reviewing this and at a minimum we also need to update `compareData_OpuDatapackVsDatim` to support COP22 OPUs. Can one of you pick up development on this ticket and complete the work and initial testing for that function. I would expect a freshly generated OPU data pack should not show any differences with what is in DATIM.

**Comment by sam-bao** [comment]
I was able to generate an OPU datapack for each country with FY23 targets without error. This does not guarantee the structure or results are correct, only that the code executed without error.

**Comment by sam-bao** [comment]
FYI @flopez-bao @JordanBalesBAO @jason-p-pickering @christian-domaas 

Not surprisingly the production app is unable to process a COP22 OPU. I am creating a new ticket dependent on this ticket to verify the app can handle cop 22 OPUs.

image

**Comment by sam-bao** [comment]
Successfully parsed the final Nigeria datapack and a Nigeria OPU datapack generated with this branch. The datim imports only differed by rows with a 0 in the datapack, which were not imported into DATIM.


Found differences between the final Zimbabwe data pack and the OPU generated with this branch. Also found differences between Namibia final data pack and OPU. AGYW differences can be ignored, they are known not to be in the OPU tool, also 0 values from datapack can be ignored, but there are a number of deduplication values that are different with no obvious explanation. 
image


Unable to parse a COP22 final data pack for South Africa as part of this testing, a separate ticket was created for that.

**Comment by jacksonsj** [comment]
Can confirm that dedupes are definitely getting dropped somewhere. Have narrowed it down to within `packPSNUxIM`, around where the dataframe called `right_side` gets created. Still investigating

**Comment by jacksonsj** [comment]
Latest commits fix the dedupe issues:

Screen Shot 2022-09-23 at 13 02 48

**Comment by sam-bao** [comment]
@jacksonsj @christian-domaas @jason-p-pickering 

In ongoing testing of this PR, it appears there may be an issue with the handling of 50+ age categories.

In the final Mali data pack the 65+ age category (and other finer ages) only appear for TX_CURR:
image

But in the test OPU datapack generated with this branch, those finer ages are appearing for other indicators, most likely erroneously:

image

**Pull request closed without merging**
