### PR TITLE
Releases/4 2 2

### PR DESCRIPTION
**Pull request by jacksonsj**
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Affected Process Elements
- [ ] Data Pack generation
- [ ] Data Pack model
- [ ] Data Pack self-service app
- [ ] Data Pack processing
- [ ] Site Tool model/distribution
- [ ] Site Tool generation (from Data Pack)
- [ ] Site Tool generation (from DATIM - for OPUs)
- [ ] Site Tool self-service app
- [ ] Site Tool to Data Pack comparison self-service app
- [ ] Site Tool to DATIM comparison self-service app
- [ ] Site Tool processing
- [ ] Site Tool import

## Types of changes

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Final Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jacksonsj** [comment]
@sam-bao @maxwellchandler - Ready for your review and testing.

I'll resolve conflicting files tomorrow.

**Comment by jacksonsj** [comment]
@jason-p-pickering - In particular, would like your review of the updates to `createAnalytics`

**Comment by sam-bao** [comment]
@jacksonsj quite a conflicts to clear. Wan't certain on all of them so I think you will need to resolve them.

**Comment by sam-bao** [comment]
@jason-p-pickering I think most of the changes you have made on this PR would have been resolved by resolving the conflicts. Perhaps you and Scott can look at them together and clear them before you make any more commits.

**Comment by jacksonsj** [comment]
ok @sam-bao @jason-p-pickering @maxwellchandler - Conflicts resolved. Ready for testing and review.

**Comment by jacksonsj** [comment]
Closing and will check `4-2-2` into `4-2-4`

**Pull request closed without merging**
