### PR TITLE
Separate writing and parsing functions

### PR DESCRIPTION
**Pull request by jacksonsj**
## Summary of Proposed Changes
- Separates writing and parsing functions `unPackTool` and `writePSNUxIM`
- Comments out NA stripping until further testing can be completed.
- Updates cached PSNUs to catch changes in India hierarchy
- Updates map to DATIM to add FSW back in
- Allow archiving of snuxim_model_data for troubleshooting purposes
- Accommodate cases where no snuxim_model_data available.

## Affected Process Elements
- [x] Data Pack generation
- [ ] Data Pack model
- [x] Data Pack self-service app
- [x] Data Pack processing
- [ ] Site Tool model/distribution
- [ ] Site Tool generation (from Data Pack)
- [ ] Site Tool generation (from DATIM - for OPUs)
- [ ] Site Tool self-service app
- [ ] Site Tool to Data Pack comparison self-service app
- [ ] Site Tool to DATIM comparison self-service app
- [ ] Site Tool processing
- [ ] Site Tool import

## Types of changes

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

## Related Issues
- Resolves pepfar-datim/COP-Target-Setting#649
- Resolves pepfar-datim/COP-Target-Setting#653
- Resolves pepfar-datim/COP-Target-Setting#657

## Final Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jacksonsj** [comment]
Current conflicts are due to master not yet including changes to template pushed as part of PR 112. Once that PR is merged, these conflicts should resolve themselves.

**Comment by sam-bao** [comment]
@jacksonsj do you have a local commit? I don't see the commenting out of the NA code?

**Comment by jacksonsj** [comment]
https://github.com/pepfar-datim/datapackr/blob/6036bac4684fe76b8e1a510858a34911a5dedfe3/R/writePSNUxIM.R#L33

**Comment by sam-bao** [comment]
@jacksonsj I repacked the PSNUxIM tab for Botswana: https://datim.zendesk.com/agent/tickets/32190 message time 23:20.

It looks like new rows are bening added that should pull in a new mechanism, but the new mechanism isn't being added to column header.

image

**Comment by jason-p-pickering** [comment]
Seems to be a remaining conflict in a support file, but this does seem to work with the self-service app.

**Comment by jacksonsj** [comment]
@sam-bao - Please test again using that Botswana Data Pack and confirm the changes I've just pushed fix the issues you were seeing

**Comment by sam-bao** [comment]
@jacksonsj Running into an issue adding an initial PSNUxIM tab: https://github.com/pepfar-datim/COP-Target-Setting/issues/669

**Comment by jacksonsj** [comment]
@sam-bao - Please test again. I've just merged the `gh660-Irum-Validations` branch in, so this should fix the issue you were seeing, plus everything in the `Code Review` column

**Comment by sam-bao** [comment]
PSNUxIM packing and repacking to be tested in master. Merging now so the validations in his branch can get into production. The packing and repacking are not available in the app, so testing these features can safely occur after the merge.

**Pull request merged**
