### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by jason-p-pickering**
### Related Issues
- Upgrades all dependencies to latest versions on CRAN
- Updates base R version to 4.3.2
- Excludes two new linters which we will need to deal with at some point in time

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

### CODE REVIEW

**Comment by JordanBalesBAO** [comment]
Is this ready for review @jason-p-pickering ?

**Comment by jason-p-pickering** [comment]
@JordanBalesBAO yes, read for review.

**Comment by jason-p-pickering** [comment]
@JordanBalesBAO I think these should be merged into the `dev` branch, but there are some merge conflicts around the DESCRIPTION and NEWS.md. Can you resolve these as I am not sure exactly how you would like to handle this.

**Comment by JordanBalesBAO** [comment]
NOTE decided to hold off on merging this dependency updates until imports are completed for 2024

**Comment by jason-p-pickering** [comment]
Closing this as I think its easier to redo from the current dev.

**Pull request closed without merging**
