### PR TITLE
DP-609: Retire internal API utility functions

### PR DESCRIPTION
**Pull request by cnemarich**
### Summary of Proposed Changes
Removes `api_version`, `api_get`, `api_filter`, `api_fields`, and `api_call` as all of their usages have been replaced by `datimutils` functions.

### Related Issues
- DP-609.

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

### CODE REVIEW

**Comment by jason-p-pickering** [comment]
@cnemarich I had a look at this, fixed some merge conflicts, and pushed my updates. 

I am not sure about the change which automatically refreshes the PSNU cached file. I see no reason that this file would become stale after one day. Changes to the PSNU list is something which does not happen often, and when it does, we usually need to carefully control how it gets released. This is a little different than the logic for mechanisms, when we know that the list changes often.  

So, while I agree with the intent of removing the `api_get` functions and so forth, are we perhaps going a bit too far with this one? 

There is still a failing test..

```
── Error (test-get-code-list.R:6:5): We can get a list of PSNUs from DATIM ─────
Error in `fetch_fresh_psnus(stale_countries, include_mil, include_DREAMS, 
    additional_fields, d2_session)`: object 'missing_country_uids' not found
Backtrace:
 1. datapackr::getPSNUs(...)
      at test-get-code-list.R:6:4
 2. datapackr fetch_fresh_psnus(...)
      at datapackr/R/getPSNUs.R:132:2

```

which I am not totally sure how to fix. Lets discus on the next call.

**Comment by jason-p-pickering** [comment]
And what is the difference between [this PR](https://github.com/pepfar-datim/datapackr/pull/518) which seems to do the same thing (at least in the title...)?

**Comment by jacksonsj** [comment]
Need to wait until DP-768 is in `dev` and then can rework this to go into `dev` afterward. May need to separate this out into a couple different PRs by theme.

**Comment by jason-p-pickering** [comment]
Converting this to draft. Agree with @jacksonsj that given the changes in DP-768, it may be more trouble than its worth to try and merge this one.

**Comment by jason-p-pickering** [comment]
Closing this as OBE. We wills start fresh from a new branch of dev.

**Pull request closed without merging**
