### PR TITLE
Release 6.1.1

### PR DESCRIPTION
**Pull request by JordanBalesBAO**
## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

### CODE REVIEW

**Comment by JordanBalesBAO** [comment]
Please do not merge until I get a chance to update news.md

**Comment by JordanBalesBAO** [comment]
Im okay with the same methodology as last time, 2 reviewers + me == Merge

**Review by jason-p-pickering — APPROVED** [review]
Looks good to me!

**Comment by JordanBalesBAO** [comment]
Completed my second run through the code. Everything looks good to me.

One more review and good to merge

**Review by flopez-bao — APPROVED** [review]
passed on my end locally

**Comment by JordanBalesBAO** [comment]
The CI is failing, however I am going to go ahead and merge this release.  This is because Jason and I have tracked this fail issue to the CI, and 3 devs have ran the unit test locally to confirm they are all working.

**Pull request merged**
