### PR TITLE
Dp 994

### PR DESCRIPTION
**Pull request by flopez-bao**
## Developer: fausto

mirror pr into master

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

### CODE REVIEW

**Review by jason-p-pickering — CHANGES_REQUESTED** [review]
The diff looks off? I thought this ticket was only for updating the orgunits, but there are some other diffs as well, which I think have already been merged. Any idea why?

**Comment by flopez-bao** [comment]
This ticket was originally based off of master so I am not sure why if master has been merged into dev. Looking at the dev branch I see the commit changes are already for example [createDatimExport](https://github.com/pepfar-datim/datapackr/blob/dev/R/createDATIMExport.R#L37), so this seems like a bug where github thinks these are changes even though they are not? Maybe I can try regenerating the pr, what do you think?

**Comment by jason-p-pickering** [comment]
You might try merging dev into this branch. That should theoretically take care of it...I think.

**Comment by flopez-bao** [comment]
okay its running through tests, i think it seems good now

**Pull request merged**
