### PR TITLE
Add top line SUBNAT values to export

### PR DESCRIPTION
**Pull request by cnemarich**
### Related Issues
- DP-XXX
- etc.

## Reviewer:
- [ ] Tests added/updated & passing.
- [ ] Clean linting.
- [ ] Related issue ticket in Jira/GitHub.
- [ ] Documentation added/updated.
- [ ] Code conforms to style guidelines.
- [ ] Well commented.
- [ ] Updates reflected in NEWS.md.
- [ ] Build check passes.

### CODE REVIEW

**Comment by jason-p-pickering** [comment]
I think we need to consult with the DATIM and downstream teams to confirm that there is actually a need for this data. Now that we have already imported most (if not all ) DataPacks, we will probably need to wait until everything is imported. @cnemarich do you want to check with DATIM/PDAP/Program to clarify that we need these data elements before we do any more work here?

**Comment by jason-p-pickering** [comment]
Assigning to you @cnemarich for requirements clarification. If we need to do this now, we are going to need to adopt a different approach by calculating this data from the data which has already been imported. If we do not need to do it, then I think we can close this ticket.

**Comment by jason-p-pickering** [comment]
@christian-domaas I am beginning to think this is OBE. Do you or @jacksonsj have any further clarification whether these numbers needed to get into DATIM?

**Comment by JordanBalesBAO** [comment]
@christian-domaas Any thoughts or can we close this out OBE?

**Comment by jason-p-pickering** [comment]
Lets close it and revisit if there really is a need for this elsewhere than the Datapack app.

**Pull request closed without merging**
