### PR TITLE
Write all formulas on right side of PSNUxIM tab

### PR DESCRIPTION
**Pull request by jacksonsj**
- Automates writing all formulas to right side of PSNUxIM tab.
- Does not fully address all performance implications of this automation.

### CODE REVIEW

**Comment by jacksonsj** [comment]
@jason-p-pickering - Could you review this to include in `dev`?

**Comment by jason-p-pickering** [comment]
@jacksonsj I tested this branch with the app, and did not see any difference in the formulas in the columns to the right. Could you confirm that this patch does what its supposed to?

I think we share concerns about the amount of time which this will add to the processing of the PSNUxIM tabs, so having some indication of how much longer it will take would be good as well. On my local machine with the app, the Malawi datapack took about 1 minute 40 seconds to generate. Could you include the differences in processing time as well, once you confirm things are working as intended?

**Comment by jacksonsj** [comment]
@jason-p-pickering - I think we discussed this on our standup last week, but this only automates dragging formulas down for any rows actively being edited by the app. So if a file already has rows written in, and the app is only adding to the bottom, this script change only adds formulas for those rows added to the bottom — not the others previously there.

Any hesitations on me pushing this to `dev`?

**Comment by jason-p-pickering** [comment]
No. I agree that this address the situation which you outline.  

Just thinking out loud however, could we just add an integrity check here to check for the presence of the formulas? I am a bit surprised that this would not be flagged anyway. Maybe we could just alert to the user to the situation instead and have them fix this?

I do have concerns in general about increasing the amount of time its going to take, especially now that we are like 50% of the way through COP.

**Comment by jason-p-pickering** [comment]
Looks good. Merging into dev.

**Pull request merged**
